# ------------------------- #
# OpPets by OpKarol.        #
# ------------------------- #


# Editing these values may damage all databases, config file and even server.
# DON'T TOUCH THEM!
version: 1.0
configVersion: 1.0
# Please.
# No help will be given to servers with changed versions values.


# You can touch these values now:
# ------------------------- #
# Settings section:         #
# ------------------------- #

# ------------------------- #
# Inventories section:      #
# ------------------------- #

PetMainInventory:
  #GUI TITLE: that is being shown when the inventory is open
  title: "&e&lYour pet!"
  items:
    level:
      material: "EXPERIENCE_BOTTLE"
      name: "Level and Experience"
      lore:
        - "By clicking here you can check"
        - "your pet current level and "
        - "what you get from it"
      glow: true
    name:
      material: "ANVIL"
      name: "Change name"
      lore:
        - "This button allows you to"
        - "change name of your pet"
      glow: true
    settings:
      material: "NOTE_BLOCK"
      name: "Set settings"
      lore:
        - "Customize settings for"
        - "your needs, world is open"
      glow: true
    respawn:
      material: "TARGET"
      name: "Respawn pet"
      lore:
        - "Pet got stuck, or died?"
        - "Respawn it now!"
      glow: true
LevelInventory:
  title: "&bCurrent Level of &l%pet_name%&b!"
  items:
    level:
      material: "EXPERIENCE_BOTTLE"
      name: "Current Level!"
      lore:
        - ""
        - "Your current level: %pet_level%/%max_pet_level%, %percentage_of_next_experience%%."
        - "Your pet needs %pet_experience_next% XP for next level!"
      glow: true
    informationBook:
      material: "KNOWLEDGE_BOOK"
      name: "What is this?!"
      lore:
        - "Every pet can level up when doing their job."
        - "pets can benefit you super-abilities, money"
        - "effects and more."
        - "By hovering mouse on Bottle O` Enchanting"
        - "you can get your pet`s current level,"
        - "and XP for next level."
        - "By hovering mouse on Lapis Lazuli, you"
        - "can see abilities and perks that are"
        - "unlocking with every level of your pet!"
      glow: true
    abilities:
      material: "LAPIS_LAZULI"
      name: "That's what you get!"
      lore:
        - "TO DO"
      glow: true
SettingsInventory:
  title: "&7%pet_name% &7built-in settings."
  items:
    visibleToOthers:
      material: "CUSTOM"
      name: "visibleToOthers"
      lore:
        - "TO DO"
      glow: false
    giftable:
      material: "CUSTOM"
      name: "giftable"
      lore:
        - "TO DO"
      glow: false
    glows:
      material: "CUSTOM"
      name: "glows"
      lore:
        - "TO DO"
      glow: false
    followPlayer:
      material: "CUSTOM"
      name: "followPlayer"
      lore:
        - "TO DO"
      glow: false
    teleportToPlayer:
      material: "CUSTOM"
      name: "teleportToPlayer"
      lore:
        - "TO DO"
      glow: false
    rideable:
      material: "CUSTOM"
      name: "rideable"
      lore:
        - "TO DO"
      glow: false
    otherRideable:
      material: "CUSTOM"
      name: "otherRideable"
      lore:
        - "TO DO"
      glow: false
    particlesEnabled:
      material: "CUSTOM"
      name: "particlesEnabled"
      lore:
        - "TO DO"
      glow: false
    resetSettings:
      material: "BARRIER"
      name: "resetSettings"
      lore:
        - "TO DO"
      glow: true



# ------------------------- #
# Messages section:         #
# ------------------------- #

AnvilInventories:
  RenameInventory:
    title: "&7Enter &f&lnew &7pet name!"
    thisNameIsBlocked: "&cThis name is blocked."
    nameWithSpaces: "&c Pet name can't have spaces."
    changedName: "&7Changed pet name to &f&l%new_pet_name%&7!"
    incorrectValueName: "&cInvalid value entered."
  DeleteInventory:
    title: "&7Write &f&l%pet_name%&7 to confirm &ndeleting&r &7pet."
    deletedMessage: "&7Deleted &f&l%pet_name%&7!"
    confirmMessage: "&7Write your pet name to confirm!"




