# ------------------------- #
#   OpPets by ThisOpKarol   #
# ------------------------- #

# (Recommended turning on )
# MySQL values (by default turned off, switch enabled value to true, in order to activate SQL).
sql:
  # Available types: "mysql", "flat"
  type: "mysql"
  user: "login"
  password: "password"
  url: "jdbc:mysql://localhost:3306/database"

# ------------------------- #
# Settings section:         #
# ------------------------- #

Prestiges:
  # Every skill has max level, after which pet becomes unnecessary, thanks to prestige system
  # we were able to make a never-ending farming level pet. After every pet maxed level, owner
  # can choose if they want to exchange pet into new prestige. If they do they lost every
  # statistic on pet, but they get ability to get skills rewards again, and get new prestige
  # levels. ☆
  enabled: true
  format: "&8[&l%prestige%&e&l☆&8]"

Skills:
  example_skill:
    available_pets: '[ALL]'
    # This isn't a maximum level that player can get, but it is a required level
    # from which player can prestige-up their pet.
    max_level: 5
    abilities:
      ability1:
        type: PLUGIN_CONNECTION
        connection: Vault
        options:
          action: 500
      # Custom commands will be executed by console.
      # This feature is coming soon!
      ability2:
        type: CUSTOM_COMMAND
        options:
          command: eco give %player% 500
      ability3:
        type: VANILLA_EFFECT
        options:
          effect: SPEED
          # Duration is provided in ticks, 1 second = 20 ticks.
          duration: 100
          amplifier: 1
      # Treasures will be a JSON Object
      # This feature is coming soon!
      ability4:
        type: TREASURE
        name: '&bLevel Treasure!'
        options: { }
      ability5:
        type: CUSTOM_MESSAGE
        message: '&bYou got speed effect for 100 seconds and 500$!'
    requirements:
      requirement1:
        type: PET_LEVEL
    adders:
      adder1:
        type: MINING
        materials: STONE, COBBLESTONE
        levelup:
          grantedPoints: 0
          everyAction: 0
          progressiveLevel: 32;true;up;10;true
      adder2:
        type: HARVESTING
        materials: WHEAT, SWEET_BERRY_BUSH
        levelup:
          grantedPoints: 0
          everyAction: 0
          progressiveLevel: 32;true;up;10;true
      adder3:
        type: CRAFTING
        materials: ALL
        levelup:
          grantedPoints: 0
          everyAction: 0
          progressiveLevel: 32;true;up;10;true
      adder4:
        type: SMELTING
        materials: ALL
        levelup:
          grantedPoints: 0
          everyAction: 0
          progressiveLevel: 32;true;up;10;true
      adder5:
        type: FISHING
        materials: ALL
        levelup:
          grantedPoints: 0
          everyAction: 0
          progressiveLevel: 32;true;up;10;true

# ------------------------- #
# Others section:           #
# ------------------------- #

Pets:
  # AXOLOTL (1.17+)
  AXOLOTL:
    special_ability:
      - STOP_ATTACK
    speed: 1.9
    # Distance is a float value after which a from player distance, entity will be teleported.
    distance: 30
  CAT:
    special_ability:
      - ACTIONBAR:&7Your pet likes fish!
      - ADD_FOOD:10
    speed: 1.9
    distance: 30
  CHICKEN:
    special_ability:
      - STOP_FALL_DAMAGE
    speed: 1.9
    distance: 30
  COW:
    special_ability:
      - CURE
      - ACTIONBAR:&7Your pet cured you!
    speed: 1.9
    distance: 30
  DONKEY:
    special_ability:
      - STOP_KNOCKBACK
    speed: 1.9
    distance: 30
  FOX:
    special_ability:
      - INVINCIBLE:100
      - ACTIONBAR:&7Your pet gives you invincibility!
    speed: 1.9
    distance: 30
  # GOAT (1.17+)
  GOAT:
    special_ability:
      - EXP:100
    speed: 1.9
    distance: 30
  HORSE:
    special_ability:
      - ADD_HEALTH:5
      - ACTIONBAR:&7Your pet supported your health!
    speed: 1.9
    distance: 30
  LLAMA:
    special_ability:
      - STOP_ATTACK
      - ACTIONBAR_AFTER:&7You survived it!
    speed: 1.9
    distance: 30
  MULE:
    special_ability:
      - FLAME:100
      - ACTIONBAR_AFTER:&7Die in flames!
    speed: 1.9
    distance: 30
  MUSHROOM_COW:
    special_ability:
      - ADD_FOOD:10
      - ACTIONBAR:&7Your pet cooked some food for you!
    speed: 1.9
    distance: 30
  OCELOT:
    special_ability:
      - FIREBALL
      - ACTIONBAR:&7Your pet exploded!
    speed: 1.9
    distance: 30
  PANDA:
    special_ability:
      - EXP:100
    speed: 1.9
    distance: 30
  PARROT:
    special_ability:
      - LIGHTING
      - ACTIONBAR_AFTER:&7Electrons!
    speed: 1.9
    distance: 30
  PIG:
    special_ability:
      - ADD_HEALTH:10
      - ACTIONBAR:&7Your pet gave you a lot of health!
    speed: 1.9
    distance: 30
  POLAR_BEAR:
    special_ability:
      - STEAL_HEALTH:3
      - ACTIONBAR_AFTER:&7You stole a lot of health!
    speed: 1.9
    distance: 30
  RABBIT:
    special_ability:
      - STOP_FALL_DAMAGE
      - ACTIONBAR_AFTER:&7What a cat!
    speed: 1.9
    distance: 30
  SHEEP:
    special_ability:
      - ADD_FOOD:10
      - ACTIONBAR:&7Your pet gave you fish!
    speed: 1.9
    distance: 30
  TURTLE:
    special_ability:
      - STOP_ATTACK
      - ACTIONBAR_AFTER:&7Ninja's reflex!
    speed: 1.9
    distance: 30
  WOLF:
    special_ability:
      - STEAL_HEALTH:3
      - ACTIONBAR_AFTER:&7You stole a lot of health!
    speed: 1.9
    distance: 30