# ------------------------- #
#   OpPets by ThisOpKarol   #
# ------------------------- #

# You can touch these values ->:

# MySQL values (by default turned off, switch enabled value to activate SQL).
# Current version doesn't support mysql, will be supported in the next versions (Most of the code is done, but I want to make sure that everything works)
# mysql:
#   enabled: false
#   host: "localhost"
#   port: "3306"
#   database: "your_database"
#   login: "user"
#   password: "password"
#   table: "OpPets"
#   driver: "mysql"

# ------------------------- #
# Settings section:         #
# ------------------------- #

Skills:
  example_skill:
    available_pets: "[ALL]"      # [AXOLOTL, COW, others]
    abilities:
      abilitity1:
        type: "CUSTOM_COMMAND"
        command: "/some-command"
    requirements:
      requirement1:
        type: "PET_LEVEL"
    boosters:

    adders:
      adder1:
        type: "MINING"
        levelup:
          grantedPoints: 1.0
          everyAction: 0
          # If you want progressiveLevel enabled, set everyAction to 0
          # e = start value, cv = change value, ud = up/down, v = value
          # %i = current start value = e, r = rounding to bigger number
          # 4th parameter is a grow-up in percentage e.g: 15[%] + level
          #                 /e/cv/ud,    by/v/  /r/
          progressiveLevel: "32;true;up;15;true"

# ------------------------- #
# Inventories section:      #
# ------------------------- #

PetMainInventory:
  #GUI TITLE: that is being shown when the inventory is open
  title: "&e&lYour pet!"
  items:
    level:
      material: "EXPERIENCE_BOTTLE"
      name: "&aLevel and Experience"
      lore:
        - "&7By clicking here you can check"
        - "&7your pet current level and "
        - "&7what you get from it"
      glow: true
    name:
      material: "ANVIL"
      name: "&aChange name"
      lore:
        - "&7This button allows you to"
        - "&7change name of your pet"
      glow: true
    settings:
      material: "NOTE_BLOCK"
      name: "&aSet-up settings"
      lore:
        - "&7Customize settings for"
        - "&7your needs, world is open"
      glow: true
    respawn:
      material: "TARGET"
      name: "&aRespawn your pet!"
      lore:
        - "&7Pet got stuck, or died?"
        - "&7Respawn it now!"
      glow: true
LevelInventory:
  title: "&bCurrent Level of &l%pet_name%&b!"
  items:
    level:
      material: "EXPERIENCE_BOTTLE"
      name: "&aCurrent Level!"
      lore:
        - ""
        - "&7Your current level: &f&l%pet_level%&7/&f&l%max_pet_level%&7, &f&l%percentage_of_next_experience%."
        - "&7Your pet needs &f&l%pet_experience_next% &7XP for next level!"
        - ""
      glow: true
    informationBook:
      material: "KNOWLEDGE_BOOK"
      name: "&aWhat is this?!"
      lore:
        - "&7Every pet can level up when doing their job."
        - "&7pets can benefit you super-abilities, money"
        - "&7effects and more."
        - "&7By hovering mouse on Bottle O` Enchanting"
        - "&7you can get your pet`s current level,"
        - "&7and XP for next level."
        - "&7By hovering mouse on Lapis Lazuli, you"
        - "&7can see abilities and perks that are"
        - "&7unlocking with every level of your pet!"
      glow: true
    abilities:
      material: "LAPIS_LAZULI"
      name: "&aThat's what you get!"
      lore:
        - "TO DO"
      glow: true
SettingsInventory:
  title: "&7%pet_name% &7built-in settings."
  items:
    visibleToOthers:
      material: "CUSTOM"
      name: "&aPet visible to others"
      lore:
        - "&8By pressing this button you"
        - "&8can switch on/off setting value"
        - "&8from the name &7(visibleToOthers)"
        - "&7Current state: &f&l%state_visibleToOthers%"
      glow: false
    giftable:
      material: "CUSTOM"
      name: "&aPet giftable"
      lore:
        - "&8By pressing this button you"
        - "&8can switch on/off setting value"
        - "&8from the name &7(giftable)"
        - "&7Current state: &f&l%state_giftable%"
      glow: false
    glows:
      material: "CUSTOM"
      name: "&aPet glows"
      lore:
        - "&8By pressing this button you"
        - "&8can switch on/off setting value"
        - "&8from the name &7(glows)"
        - "&7Current state: &f&l%state_glows%"
      glow: false
    followPlayer:
      material: "CUSTOM"
      name: "&aFollow player"
      lore:
        - "&8By pressing this button you"
        - "&8can switch on/off setting value"
        - "&8from the name &7(followPlayer)"
        - "&7Current state: &f&l%state_followPlayer%"
      glow: false
    teleportToPlayer:
      material: "CUSTOM"
      name: "&aTeleport to player"
      lore:
        - "&8By pressing this button you"
        - "&8can switch on/off setting value"
        - "&8from the name &7(teleportToPlayer)"
        - "&7Current state: &f&l%state_teleportToPlayer%"
      glow: false
    rideable:
      material: "CUSTOM"
      name: "&aRideable"
      lore:
        - "&8By pressing this button you"
        - "&8can switch on/off setting value"
        - "&8from the name &7(rideable)"
        - "&7Current state: &f&l%state_rideable%"
      glow: false
    otherRideable:
      material: "CUSTOM"
      name: "&aOther rideable"
      lore:
        - "&8By pressing this button you"
        - "&8can switch on/off setting value"
        - "&8from the name &7(otherRideable)"
        - "&7Current state: &f&l%state_otherRideable%"
      glow: false
    particlesEnabled:
      material: "CUSTOM"
      name: "&aParticles enabled"
      lore:
        - "&8By pressing this button you"
        - "&8can switch on/off setting value"
        - "&8from the name &7(particlesEnabled)"
        - "&7Current state: &f&l%state_particlesEnabled%"
      glow: false
    resetSettings:
      material: "BARRIER"
      name: "&cReset settings"
      lore:
        - "&8By pressing this button you"
        - "&8can reset settings of this pet"
        - "&8/ return to default settings."
      glow: true
GuestInventory:
  title: "&7%pet_name%&7`s stats!"
  items:
    level:
      material: "EXPERIENCE_BOTTLE"
      name: "&aLevel and Experience"
      lore:
        - ""
        - "&7Pet current level: &f&l%pet_level%&7/&f&l%max_pet_level%&7, &f&l%percentage_of_next_experience%&7."
        - "&7Pet needs &f&l%pet_experience_next%&7 XP for next level!"
        - ""
      glow: true
    informationBook:
      material: "KNOWLEDGE_BOOK"
      name: "&aPet's information!"
      lore:
        - "&7Owner: &f&l%pet_owner%"
        - "&7Name: &f&l%pet_name%"
        - "&7Experience: &f&l%pet_experience%"
        - "&7Level: &f&l%pet_level%"
        - "&7Type: &f&l%pet_type%"
        - "&7Skill: &f&l%pet_skill%"
      glow: true
ShopInventory:
  title: "&7Shop."
  items:
    cow:
      material: "COW_SPAWN_EGG"
      name: "&aCow"
      lore:
        - "&7Type: &f&l%type%"
        - "&7Price: &f&l%price%"
      glow: true
      options:
        # Price requires economy plugin - Vault based on OR OpEconomy
        price: 500
        type: "COW"
BuyerAdmitInventory:
  title: "&7Confirm purchase!"
  items:
    confirm:
      material: "GREEN_WOOL"
      name: "&aConfirm"
      lore:
        - "Press this button to confirm"
        - "purchasing this pet"
      glow: true
    decline:
      material: "RED_WOOL"
      name: "&cDecline"
      lore:
        - "Press this button to decline"
        - "purchasing this pet"
      glow: true
    informationBook:
      material: "KNOWLEDGE_BOOK"
      name: "&7Purchase information!"
      lore:
        - "&7Price: &f&l%price%"
        - "&7Type: &f&l%type%"
      glow: true

# ------------------------- #
# Messages section:         #
# ------------------------- #

AnvilInventories:
  RenameInventory:
    title: "&7Enter &f&lnew &7pet name!"
    thisNameIsBlocked: "&cThis name is blocked."
    nameWithSpaces: "&c Pet name can't have spaces."
    changedName: "&7Changed pet name to &f&l%new_pet_name%&7!"
    incorrectValueName: "&cInvalid value entered."
    noPermission: "&cYou don't have permission: &f&l%permission%&c."
  DeleteInventory:
    title: "&7Write &f&l%pet_name%&7 to confirm &ndeleting&r &7pet."
    deletedMessage: "&7Deleted &f&l%pet_name%&7!"
    confirmMessage: "&7Write your pet name to confirm!"


