# ------------------------- #
#   OpPets by ThisOpKarol   #
# ------------------------- #

# (Recommended turning on )
# MySQL values (by default turned off, switch enabled value to true, in order to activate SQL).
sql:
  # Available types: "mysql", "flat"
  type: "flat"
  user: "login"
  password: "password"
  url: "jdbc:mysql://localhost:3306/database"

# ------------------------- #
# Settings section:         #
# ------------------------- #

Prestiges:
  # Every skill has max level, after which pet becomes unnecessary, thanks to prestige system
  # we were able to make a never-ending farming level pet. After every pet maxed level, owner
  # can choose if they want to exchange pet into new prestige. If they do they lost every
  # statistic on pet, but they get ability to get skills rewards again, and get new prestige
  # levels. ☆
  enabled: true
  format: "&8[&l%prestige%&e&l☆&8]"

# ------------------------- #
# Others section:           #
# ------------------------- #

Pets:
  # AXOLOTL (1.17+)
  AXOLOTL:
    special_ability:
      - STOP_ATTACK
    speed: 1.9
    # Distance is a float value after which a from player distance, entity will be teleported.
    distance: 30
  CAT:
    special_ability:
      - ACTIONBAR:&7Your pet likes fish!
      - ADD_FOOD:10
    speed: 1.9
    distance: 30
  CHICKEN:
    special_ability:
      - STOP_FALL_DAMAGE
    speed: 1.9
    distance: 30
  COW:
    special_ability:
      - CURE
      - ACTIONBAR:&7Your pet cured you!
    speed: 1.9
    distance: 30
  DONKEY:
    special_ability:
      - STOP_KNOCKBACK
    speed: 1.9
    distance: 30
  FOX:
    special_ability:
      - INVINCIBLE:100
      - ACTIONBAR:&7Your pet gives you invincibility!
    speed: 1.9
    distance: 30
  # GOAT (1.17+)
  GOAT:
    special_ability:
      - EXP:100
    speed: 1.9
    distance: 30
  HORSE:
    special_ability:
      - ADD_HEALTH:5
      - ACTIONBAR:&7Your pet supported your health!
    speed: 1.9
    distance: 30
  LLAMA:
    special_ability:
      - STOP_ATTACK
      - ACTIONBAR_AFTER:&7You survived it!
    speed: 1.9
    distance: 30
  MULE:
    special_ability:
      - FLAME:100
      - ACTIONBAR_AFTER:&7Die in flames!
    speed: 1.9
    distance: 30
  MUSHROOM_COW:
    special_ability:
      - ADD_FOOD:10
      - ACTIONBAR:&7Your pet cooked some food for you!
    speed: 1.9
    distance: 30
  OCELOT:
    special_ability:
      - FIREBALL
      - ACTIONBAR:&7Your pet exploded!
    speed: 1.9
    distance: 30
  PANDA:
    special_ability:
      - EXP:100
    speed: 1.9
    distance: 30
  PARROT:
    special_ability:
      - LIGHTING
      - ACTIONBAR_AFTER:&7Electrons!
    speed: 1.9
    distance: 30
  PIG:
    special_ability:
      - ADD_HEALTH:10
      - ACTIONBAR:&7Your pet gave you a lot of health!
    speed: 1.9
    distance: 30
  POLAR_BEAR:
    special_ability:
      - STEAL_HEALTH:3
      - ACTIONBAR_AFTER:&7You stole a lot of health!
    speed: 1.9
    distance: 30
  RABBIT:
    special_ability:
      - STOP_FALL_DAMAGE
      - ACTIONBAR_AFTER:&7What a cat!
    speed: 1.9
    distance: 30
  SHEEP:
    special_ability:
      - ADD_FOOD:10
      - ACTIONBAR:&7Your pet gave you fish!
    speed: 1.9
    distance: 30
  TURTLE:
    special_ability:
      - STOP_ATTACK
      - ACTIONBAR_AFTER:&7Ninja's reflex!
    speed: 1.9
    distance: 30
  WOLF:
    special_ability:
      - STEAL_HEALTH:3
      - ACTIONBAR_AFTER:&7You stole a lot of health!
    speed: 1.9
    distance: 30