name: OpPets
version: '${project.version}'
main: me.opkarol.oppets.OpPets
api-version: 1.13
authors: [ OpKarol, ThisOpKarol, NotOpKarol ]
softdepend:
  - MySQL

commands:
  oppets:
    description: "Main command"
