name: OpPets
version: '${project.version}'
main: me.opkarol.oppets.OpPets
api-version: 1.16
authors: [ OpKarol, ThisOpKarol, NotOpKarol ]
softdepend: [ Vault ]
libraries: [com.zaxxer:HikariCP:5.0.1]

commands:
  oppets:
    description: "OpPets core command. Used to do everything with using your pet up to managing it."


